services:
  synaptechs:
    build: .
    ports:
      - target: 80
        published: 8501
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G